CREATE TABLE SaldoConto
(
    IDConto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Saldo DOUBLE
);

CREATE TABLE Cliente
(
    IDCliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserCliente VARCHAR(64),
    PswCliente VARCHAR(64),
    IDContoC INTEGER,
    FOREIGN KEY(IDContoC) REFERENCES SaldoConto(IDConto)
);

CREATE TABLE Venditore
(
    IDVenditore INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserVenditore VARCHAR(64),
    PswVenditore VARCHAR(64),
    IDContoV INTEGER,
    FOREIGN KEY(IDContoV) REFERENCES SaldoConto(IDConto)
);

CREATE TABLE Oggetti
(
    IDOggetto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NomeOggetto VARCHAR(64),
    ImmagineURL VARCHAR(128),
    Descrizione VARCHAR(1024),
    PrezzoOggetto DOUBLE,
    Quantita INTEGER,
    IDVend INTEGER,
    FOREIGN KEY (IDVend) REFERENCES Venditore(IDVenditore)
);


/*------INSERT-------*/

INSERT INTO SaldoConto (IDConto,Saldo)
VALUES (default,666.00),
       (default,105.00),    
       (default,1500.00),  
       (default,3000.50), 
       (default,300.50),    
       (default,70500.00),
       (default,50.00);

INSERT INTO Venditore (IDVenditore,UserVenditore,PswVenditore,IDContoV)
VALUES (default,'Luffy','gomugomu',4),
       (default,'BarnySt','Leggendario',5),
       (default,'Genny','savastano',6);

INSERT INTO Cliente (IDCliente,UserCliente,PswCliente,IDContoC)
VALUES (default,'KatyManca','Molto123',1),
       (default,'HarriP','Sorbettoallimone',2),
       (default,'Khaleesi','dracarys',3),
       (default,'tizio','1234',7);
       

INSERT INTO Oggetti (IDOggetto, NomeOggetto, ImmagineURL, Descrizione , PrezzoOggetto , Quantita , IDVend)
VALUES
(default,'Funko Pop: Batman','Immagini/FPBat.jpg','Adorabile Action Figure di Batman',15.00,5,1),
(default,'OP V.1','Immagini/OPv1.png','Primo volume della saga manga di One Piece',3.50,10,2),
(default,'Cable & Deadpool 2','Immagini/C&D2.jpg','Fumetto Cable & Deadpool 2',3.50,10,3),
(default,'Sailor Moon','Immagini/SailorMoon.jpg','Action Figure Sailor Moon',30.00,2,2),
(default,'Uncharted Drake Collection','Immagini/uncharted.jpg','Uncharted Drake Collection',45.50,3,1);






